version: "2"
services:
  test:
    image: test_graphql_frontend
    build:
      context: .
      dockerfile: Dockerfile-test.x64
    volumes:
      - .:/graphql_frontend
    network_mode: host

  graphql_frontend:
    image: graphql_frontend
    build:
      context: .
      dockerfile: Dockerfile.x64
    ports:
      - "5001:5001"
